### ISSUE TITLE
 Network Error

### ISSUE THREAD

**Issue by alanhg** [jfairbank/redux-saga-test-plan#273] opened 2019-05-07 15:30 UTC
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchErrornode_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
        at Request.client.on.errnode_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
        at Request.emit (events.js:187:15)
        at Request.onRequestError (/node_modules/request/request.js:881:8)
        at ClientRequest.emit (events.js:182:13)
        at Socket.socketErrorListener (_http_client.js:382:9)
        at Socket.emit (events.js:182:13)
        at emitErrorNT (internal/streams/destroy.js:82:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
        at process._tickCallback (internal/process/next_tick.js:63:19) undefined

**Comment by jp928** [comment] 2019-05-08 04:24
@alanhg I don't think this issue was caused by this library. Close this issue.

**Closed by jp928** 2019-05-08 04:24 UTC
