### ISSUE TITLE
Actual effect seems to have extra key

### ISSUE THREAD

**Issue by samtgarson** [jfairbank/redux-saga-test-plan#31] opened 2016-11-06 18:02 UTC
(This seems similar to #4)

Saga code:
```javascript
...
import { put, call, take } from 'redux-saga/effects'

export default function* initializeApp () {
  yield take(INITIALIZE_APP)
  yield put(showLoader())
  yield [call(initializeUser), call(bootstrapData)]
  yield put(hideLoader())
}
```
Test code:
```javascript
...
import testSaga from 'redux-saga-test-plan'

describe('initializeApp', () => {
  let generator;
  beforeEach (() => { 
    generator = testSaga(initializeApp)
  });

  it('fetches user and bootstraps in parallel', () => {
    generator.next().take(INITIALIZE_APP)
    generator.next().put(showLoader());
    generator.next().parallel(bootstrapData, initializeUser)
  })
})
```

I'm getting an error on the first `take`:

```
Assertion 1 failed: take effects do not match

Expected
--------
{ pattern: 'INITIALIZE_APP' }

Actual
------
{ channel: null, pattern: 'INITIALIZE_APP' }
```

Not sure how this is possible given what's said in #4 that the test saga delegates to the original method... Has Redux Saga updated to include this extra key?

Has anyone seen this before? Cheers!

**Comment by jfairbank** [comment] 2016-11-07 13:38
Hi @samtgarson!

Based on #4 and this issue, it looks to me like there is an edge case version issue between what application code uses and what test plan uses. Can you provide me a few things please?

What environment are you running in your tests in? Node or browser (karma, webpack, etc.)?
What are your Node and npm versions?
What version of redux-saga are you using?
What version of redux-saga-test-plan are you using?
What is the output of `npm ls`?

Thanks!

**Comment by jfairbank** [comment] 2016-11-16 14:21
Hi again @samtgarson.

I peaked at your public repos, and if your particular issue is with https://github.com/samtgarson/lunar-and-flo-mobile, then I think I know what the problem is.

In the root of your repo, you have a package.json file that specifies redux-saga 0.12 and redux-saga-test-plan 1.3.1: https://github.com/samtgarson/lunar-and-flo-mobile/blob/master/package.json#L46-L47.

However, inside your `app` folder, you have another package.json file that specifies redux-saga 0.11.1: https://github.com/samtgarson/lunar-and-flo-mobile/blob/master/app/package.json#L25.

Assuming you have installed dependencies in both the root folder and `app` folder, you'll have two `node_modules` folders. Therefore, I think your application code is pulling redux-saga 0.11.1 from `app/node_modules` while redux-saga-test-plan is resolving to redux-saga 0.12.0 in your root `node_modules`. I believe the `channel` property was introduced in 0.12.0 too.

Can you try consolidating your redux-saga and redux-saga-test-plan dependencies in only one package.json file to see if that fixes your problem?

Thanks!

**Comment by jfairbank** [comment] 2016-12-12 14:54
Closing due to inactivity. Please let me know if the suggested fix doesn't work.

**Closed by jfairbank** 2016-12-12 14:54 UTC

**Comment by samtgarson** [comment] 2017-01-03 11:27
@jfairbank that seemed to be it, thanks for investigating! The dual package.jsons were confusingly generated from https://github.com/bakery/baker which I've since yanked out anyway.
