### ISSUE TITLE
Typescript error with ^4.0.0-beta.2

### ISSUE THREAD

**Issue by francoiscabrol** [jfairbank/redux-saga-test-plan#246] opened 2019-02-06 21:50 UTC
I wanted to install redux-saga-test-plan and I got some typing errors. So I tried to update the dependencies and I finally end up with the following dependency versions:
"typescript": "^3.1.1",
"redux-saga": "^1.0.1",
"redux-saga-test-plan": "^4.0.0-beta.2",

and I see this type-checking error:
```
node_modules/redux-saga-test-plan/effects.d.ts:13:16 - error TS2314: Generic type 'Pattern' requires 1 type argument(s).

13     (pattern?: E.Pattern): R;
                  ~~~~~~~~~
```

I also tried with the last typescript version (3.3) and same error.

I investigated a little bit and it looks like this `Pattern` type changed 2 months ago in redux-saga (https://github.com/redux-saga/redux-saga/blob/master/packages/types/index.d.ts) but maybe the problem appears only with the recent versions of typescript...

**Comment by gilbsgilbs** [comment] 2019-02-07 13:19
Apparently, types weren't updated for 1.0.0 at all (see #201). PR #202 by @maxatwork is supposed to fix this, but seems stalled unfortunately. I think you can close this issue in favor of #201.

**Comment by jp928** [comment] 2019-02-11 06:57
I had merged #201. Close this issue.

**Comment by maracuja-juice** [comment] 2019-03-02 09:10
This issue still occurs. 
Is this issue still in the type definitions or was there no new release?

**Comment by Favna** [comment] 2019-03-13 11:21
Confirming this issue still occurs. Relevant package versions:

```json
"redux-saga-test-plan": "^4.0.0-beta.2",
"typescript": "^3.3.3333"
```

Exact Error:
```sh
TypeScript error: Generic type 'Pattern' requires 1 type argument(s).  TS2314

    11 |
    12 | interface TakeEffectApi<R> {
  > 13 |     (pattern?: E.Pattern): R;
       |                ^
    14 |     <T>(channel: Channel<T>): R;
    15 | }
    16 | interface PutEffectApi<R> {
```

It is temporarily resolved by adding `"skibLibCheck": true` to the `tsconfig` but this value *should* not be required for end-users

**Comment by maracuja-juice** [comment] 2019-03-30 08:45
@jp928 Can you look into this issue again?

**Comment by jp928** [comment] 2019-03-30 10:13
@maracuja-juice

Sure. Any suggestion?

**Comment by jp928** [comment] 2019-03-30 10:37
@maracuja-juice 
I had looked at it. The master branch should not have this issue because that Pattern accepts generic type T on line 3. I will bump npm version and anybody has this typescript issue can be resolved.

**Closed by jp928** 2019-03-30 10:37 UTC

**Comment by jp928** [comment] 2019-03-30 10:46
Sorry I forgot to mention that I don't have permission to release this on npm. Please reinstall the library before we release.

**Comment by maracuja-juice** [comment] 2019-03-30 12:24
@jp928 So do I understand it correctly that the issue is fixed but the fix is not released yet?

**Comment by jp928** [comment] 2019-03-30 23:06
You are right. Let me bump the version.

**Comment by maracuja-juice** [comment] 2019-04-09 17:45
So as you don't have permission to release the new version this isn't solved yet? (but the issue is closed) Or what is the current state of this issue?

**Comment by maracuja-juice** [comment] 2019-04-15 13:38
@jfairbank Hello, as you can release versions I'm trying to summon you. Would be great if you could release a new version which would finally fix this :)

**Comment by fabienchn** [comment] 2019-05-03 15:23
@jp928 any news on that ?

**Comment by Favna** [comment] 2019-05-03 17:36
@Fabienchn just set the "skipLibCheck" compiler option

**Comment by jp928** [comment] 2019-05-06 07:11
@jfairbank Can we release on npm please?

**Comment by jp928** [comment] 2019-05-06 07:15
@Favna @fabienchn  I had informed the author who has the privilege to publish to npm. It should be coming soon. Thanks for using the library.
